config/routes.rb
Rails.application.routes.draw do
  resources :cars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
	def self.search(search)
		if search
			where(["name LIKE ?" , "%#{search}%"])
		else
			all
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def index
		@cars = Car.search(params[:search])
	end

	def create
	  @car = Car.new(car_params)

      if @car.save
        render json: @car
      else
        render json: @car.errors, status: :unprocessable_entity
      end
    end

    def update
    	@car = Car.find(params[:id])
    	if @car.update(car_params)
    		render json: @car
    	else
    		render json: @car.errors, status: :unprocessable_entity
    	end
    end

    def destroy
    	@car = Car.find(params[:id])
    	@car.destroy
    	head :no_content
    end

    private
    def car_params
    	params.require(:car).permit(:name, :horsepower, :price, :model)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/index.html.erb
<%= form_tag cars_path , :method => 'get' do %>
 <%= text_field_tag :search, params[:search] %>
 <%= submit_tag "Search" %>
<% end %>

<%= react_component 'Cars', { data: @cars } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>